<template>
    <content-loader
        :height="497"
        :width="1170"
        :speed="3"
        primary-color="#f3f3f3"
        secondary-color="#ecebeb"
    >
        <rect
            x="48"
            y="21.13"
            rx="4"
            ry="4"
            width="339.07"
            height="347.28"
        /> 
        <rect
            x="49"
            y="381.13"
            rx="0"
            ry="0"
            width="76"
            height="68"
        /> 
        <rect
            x="137"
            y="381.13"
            rx="0"
            ry="0"
            width="74"
            height="68"
        /> 
        <rect
            x="224"
            y="381.13"
            rx="0"
            ry="0"
            width="77"
            height="68"
        /> 
        <rect
            x="315"
            y="381.13"
            rx="0"
            ry="0"
            width="69"
            height="68"
        /> 
        <rect
            x="429"
            y="18.13"
            rx="0"
            ry="0"
            width="728"
            height="10"
        /> 
        <rect
            x="429"
            y="39.13"
            rx="0"
            ry="0"
            width="730"
            height="10"
        /> 
        <rect
            x="429"
            y="62.13"
            rx="0"
            ry="0"
            width="505"
            height="10"
        /> 
        <rect
            x="429"
            y="103.13"
            rx="0"
            ry="0"
            width="233"
            height="42.34"
        /> 
        <rect
            x="429"
            y="170.13"
            rx="0"
            ry="0"
            width="326.2"
            height="29.34"
        /> 
        <rect
            x="829"
            y="179.13"
            rx="0"
            ry="0"
            width="239"
            height="11"
        /> 
        <rect
            x="1059"
            y="219.13"
            rx="0"
            ry="0"
            width="0"
            height="10"
        /> 
        <rect
            x="429"
            y="219.13"
            rx="0"
            ry="0"
            width="379.05"
            height="35"
        /> 
        <rect
            x="825"
            y="219.13"
            rx="0"
            ry="0"
            width="336"
            height="35"
        /> 
        <rect
            x="429"
            y="281.13"
            rx="0"
            ry="0"
            width="85"
            height="58"
        /> 
        <rect
            x="540"
            y="281.13"
            rx="0"
            ry="0"
            width="85"
            height="58"
        /> 
        <rect
            x="651"
            y="281.13"
            rx="0"
            ry="0"
            width="85"
            height="58"
        /> 
        <rect
            x="438"
            y="382.13"
            rx="0"
            ry="0"
            width="171"
            height="62"
        /> 
        <rect
            x="272"
            y="342.83"
            rx="0"
            ry="0"
            width="0"
            height="0"
        />
    </content-loader>
</template>
<script>
import { ContentLoader } from "vue-content-loader"

export default {
    components: {
        ContentLoader
    }
}
</script>
